#! /usr/bin/env ruby

require 'rubygems'
require 'main'

$:.unshift File.dirname(File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__)
require 'queryer'

possible_envs = ARGV.reject { |arg| arg =~ /(^-|.+=.+|\s+|\s|[^\w\_\-])/ }
$environment = ARGV.delete(possible_envs.first) unless possible_envs.first == ARGV.last
$queryer = Queryer.new(nil, $environment)

Main {
  keyword(:database) {
    description 'the database to query from'
    default $queryer.default(:database)
  }

  keyword(:username) {
    description 'the database user'
    default $queryer.default(:username)
  }

  keyword(:password) {
    description 'the database password for the user'
    default $queryer.default(:password)
  }

  keyword(:hostname) {
    description 'database hostname'
    default $queryer.default(:hostname)
  }

  keyword(:encoding) {
    description 'database encoding (TODO)'
    default $queryer.default(:encoding)
  }

  keyword(:adapter) {
    description 'relational database to use'
    default $queryer.default(:adapter)
  }

  option(:debug, :d) {
    description 'enable debugging outputs'
    default false
  }

  argument(:query) {
    description 'the query to perform (enclose this in quotes)'
  }

  def run
    $queryer.override_config params.to_h.inject({}) { |h, (k,v)| h[k] = v.value; h }
    $queryer.perform params[:query].value
  end
}